# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Ashley Ingenito
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://ashleyingenito.github.io" # the base hostname & protocol for the site
og_image: /assets/img/ashley.png
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
   

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: aingenito005@gmail.com
      link: mailto:aingenito005@gmail.com
  
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/ashley-ingenito/
    - name: GitHub
      link: https://github.com/ashleyingenito


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
